### ISSUE TITLE
https://palettte.app/

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#101]
**Name**
palettte.app/

**Description**
tdb

**URL**
https://palettte.app/

**Category**
design

**Comment by lizrodriguez** [comment]
As per https://www.gabrieladorf.com/palettteapp/ a good description would be "Build, analyze and edit smooth color palettes." 

If you're good with that I can add this and submit a PR @lostdesign

**Comment by lostdesign** [comment]
@lizrodriguez Yes please.

**Comment by S3B4S** [comment]
Has been added.
