### ISSUE TITLE
https://bokub.github.io/git-history-editor/

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#104]
**Name**
git-history-editor

**Description**
Messed up some of your commits? Make it undone

**URL**
https://bokub.github.io/git-history-editor/

**Category**
general

**Comment by oshka** [comment]
Should this be added to resources/general.json ?

**Comment by S3B4S** [comment]
I'd add this to `resources/utility.json` our other git related resources are in there.

**Comment by lostdesign** [comment]
^

**Comment by S3B4S** [comment]
Has been added.
