### ISSUE TITLE
Add https://cantunsee.space to Design category

### ISSUE THREAD

**Issue by barbados-clemens** [webgems/webgems#105]
**Name**
Can't Unsee

**Description**
A game where your attention to details earns you a lot of coins. WARNING: Once you see the difference between the images, you won't be able to unsee it

**URL**
https://cantunsee.space

**Category**
design

**Comment by lostdesign** [comment]
Great resource btw, i tried it myself yesterday.

**Comment by barbados-clemens** [comment]
Yeah I very much like it. I think it helps people understand the subtleties of design and grasp those concepts of making sure the "little" things are all in place.

**Comment by S3B4S** [comment]
Has been added.
