### ISSUE TITLE
Add accessibility as catagory to have related resources

### ISSUE THREAD

**Issue by vikas-parashar** [webgems/webgems#116]
**Is your feature request related to a problem? Please describe.**
There isn't a dedicated category for web accessibility related resources.

**Describe the solution you'd like**
Create a category and add resources to it. Having separate category will also help raising awareness. 

**Describe alternatives you've considered**

**Additional context**
Right now accessibility related resources(there is one, currently) are listed in general section. In my opinion, it would be better to have a section for it since there are many accessibility related resources available and it might pollute general section.

Let me know what you think. If it is doable I can also help adding resources for this category.

**Comment by lizrodriguez** [comment]
I'd like to give this a try!

**Comment by lostdesign** [comment]
Fixed in #153

**Comment by lostdesign** [comment]
@vikas-parashar if you have more A11y resources, feel free to suggest them here. The section now exists.

**Comment by lostdesign** [comment]
Going to close this meanwhile. Either comment here, create a new issue or open a PR right away.

**Comment by vikas-parashar** [comment]
Thanks! I will open separate PR for more resources.
