### ISSUE TITLE
Add image-color.com to design category

### ISSUE THREAD

**Issue by homeniukValeriy** [webgems/webgems#128]
**Name**
Image Color Picker

**Description**
Image color picker and palette generator

**URL**
https://image-color.com

**Category**
Design

**Comment by lizrodriguez** [comment]
I'll grab this one 👍

**Comment by lizrodriguez** [comment]
Nevermind, saw this was done 😁

**Comment by S3B4S** [comment]
Oh oops, it should have been closed then.
