### ISSUE TITLE
Border highlight for specific card doesn't work in production

### ISSUE THREAD

**Issue by S3B4S** [webgems/webgems#139]
**Describe the bug**

The highlight border does not show up after pasting a url with the parameter `card` in production.

**To Reproduce**

1. Visit https://webgems.io/fullstack

2. Click "copy" on a card. You should see the following:

<img width="1001" alt="Screenshot 2019-10-03 at 12 23 15" src="https://user-images.githubusercontent.com/17083334/66119492-0705df00-e5d9-11e9-806a-8334ead0803a.png">

3. This will copy the url `https://webgems.io/fullstack?card=<cardtitle>` to your clipboard, meant to be shared. If you paste the url `https://webgems.io/fullstack?card=<cardtitle>` in a new window/tab notice that the border around the referenced card is *not* highlighted.

**Expected behavior**

The expected behaviour is for the border to appear as shown in the screenshot after pasting the url `https://webgems.io/fullstack?card=egghead.io`. Weirdly enough, this does happen in development environment (eg, when running `npm run dev`).

**Comment by lostdesign** [comment]
Seems to work for me in prod and dev?

**Comment by karnthis** [comment]
This is also working for me in Prod:
https://webgems.io/fullstack/?card=egghead.io

**Comment by S3B4S** [comment]
Yeah also works now for me
