### ISSUE TITLE
Explicitly define in contributing guidelines to make a pull request for dev branch

### ISSUE THREAD

**Issue by wulforr** [webgems/webgems#147]
**Is your feature request related to a problem? Please describe.**
Beginners to open source development generally make a pull request in master branch.

**Describe the solution you'd like**
Define it in contributing guidelines to take steps for pull request and to merge in dev branch.

**Comment by wulforr** [comment]
![git](https://user-images.githubusercontent.com/41507129/66270160-af33d600-e86d-11e9-98c5-84307dd7c7d6.png)
It could be somewhat like this

**Comment by lostdesign** [comment]
Thanks and we saw that many people created PRs for the master branch. In order to make it more easy, we will accept PRs into master by changing the CI process to build on releases. Will keep this open until then and keep it as reference if we still need this.

**Comment by jgierer12** [comment]
Please consider mentioning this in the contributing guide until you change the build process, it's very annoying to make a PR against master and then realizing it should be against dev and having to rebase or merge.

**Comment by S3B4S** [comment]
> An alternative would be to make dev the default branch in the meantime, as most other projects using git flow do.

How do you configure this on GitHub? I've tried to look into options to not allow PRs to master or to make it clear that if you make a PR it should be to dev (besides CONTRIBUTING.md) but could not find such a thing. So I'm genuinely curious about this.

**Comment by jgierer12** [comment]
It's under Settings > Branches:

![image](https://user-images.githubusercontent.com/4331946/66754437-3d274680-ee96-11e9-9e15-12b6076c7f18.png)

**Comment by S3B4S** [comment]
Great! @lostdesign we could do this in the meantime until we've configured Continuous Deployment to rebuild on releases.

**Comment by lostdesign** [comment]
Doing that now.
