### ISSUE TITLE
Add resource Goodbrief

### ISSUE THREAD

**Issue by b3u** [webgems/webgems#149]
**Name**
goodbrief

**Description**
GoodBrief is a random generator for design briefs. Choose the type of creative work and the industry, and goodbrief will generate a unique brief.

**URL**
http://goodbrief.io

**Category**
design

**Comment by lostdesign** [comment]
Good find.

**Comment by b3u** [comment]
Can i take care of this issue (bc of Hacktoberfest ;) )?

**Comment by lostdesign** [comment]
Sure, shoot a PR.
