### ISSUE TITLE
New Category with youtubers

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#155]
**Describe the solution you'd like**
Add a youtubers teaching design and dev.

Here are a couple I'd already add:
Traversy Media: https://www.youtube.com/user/TechGuyWeb
Wesbos: https://www.youtube.com/user/wesbos
Leveluptuts: https://www.youtube.com/user/LevelUpTuts
Devtips: https://www.youtube.com/user/DevTipsForDesigners
The net ninja: https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg
thefutur: https://www.youtube.com/channel/UC-b3c7kxa5vU-bnmaROgvog
Steve Schoger: https://www.youtube.com/channel/UCxqiDtkXtOCNJdckODHk9YA

**Comment by Johan-Ng** [comment]
Which file should i add youtubers to?

**Comment by lostdesign** [comment]
Hi @Johan-Ng thanks for your interest in this. You would basically need to do the same as in #153. 

Create a file in `resources` called `resources/youtube.json` and then register it in `resources/index.js`. Copy the format from other `.json` files there and add the necessary text there as given. In the readme there is also an example of how a resource looks like.

No need to all of them. Creating the category and adding at least one resource would be fine already. Rather have one complete resource than half finished ones. Tags can be ignored as of now.

**Comment by Johan-Ng** [comment]
@lostdesign Thank you!

**Comment by S3B4S** [comment]
I'm not really sold on the idea of having a seperate youtube category, I feel like most youtubers themselves can be categorised into current existing categories (such as "design", "general", "php"). I think if we'd have tags we could add a #youtube tag so if anyone wants to see youtubers they can look for the tag.

**Comment by karnthis** [comment]
I agree with S3B4S on this, YouTube is the medium of the resource, not what the resource actually is for.

**Comment by Johan-Ng** [comment]
@S3B4S do you mean i should add a line for categories(e.g. "design", "html", etc.) and a line for "#youtube tag"? Can you give me some clue like what should the "#youtube tag" be like? Thank you!

**Comment by lostdesign** [comment]
Youtubers don‘t have just one type of content when they are teaching dev. You could put them into every single of them. Only thefutur and Steve Schoger could be put into design. Traversy, Leveluptuts, the net ninja, devtips and thecodingtrain would not fit into one lang at all.

**Comment by S3B4S** [comment]
I see your point, I still think it feels weird to have a category called "youtube(rs)". I'd be more in favor of naming such as "content creators" and in there we can also include other content creators that do not use YouTube as their medium.

**Comment by lostdesign** [comment]
Yeah the name should be **content creators**. Getify on twitter then could also be listed and others, since they post nice short tips and other things often.

**Comment by Johan-Ng** [comment]
Sure, I'll change the name of the file. I seldomly use tag but I'll try my
best for it. Can you tell me what have I done wrong in index.js? It says I
can't pass the checks. Thank you so much to all of you!

**Comment by S3B4S** [comment]
Regarding
> do you mean i should add a line for categories(e.g. "design", "html", etc.) and a line for "#youtube tag"? Can you give me some clue like what should the "#youtube tag" be like? Thank you!

What I meant was to add a `youtube` tag to each `tags` field of a given category. There's a planned feature that adds a search option to webgems so people can search for keywords and/or tags.

> Can you tell me what have I done wrong in index.js? It says I
can't pass the checks. Thank you so much to all of you!

In PRs #158 and #159 it isn't passing because the `youtube.json` is missing, which you did not include in the commit. #157 seems to be the succesfull version of this, which does include the `youtube.json`. We'll just close #158 #159 and continue with #157

**Comment by S3B4S** [comment]
^ My bad, misclicked on the phone.

Also, I think we totally should add these two:
Funfunfunction, https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q
Mayuko, https://www.youtube.com/user/hellomayuko

**Comment by Johan-Ng** [comment]
https://github.com/webgems/webgems/pull/161#issue-327546871

**Comment by Johan-Ng** [comment]
@S3B4S @karnthis @lostdesign Thank you very much for giving me guidance and support throughout the task. I will treasure this experience and continue to work hard. I wish you all the best for your careers and thank you once again for spending your time helping me!

**Comment by S3B4S** [comment]
So this has been added, thanks @Johan-Ng!

**Comment by lostdesign** [comment]
So basically, there is a PR here referenced that would have been merged but had to be reverted due to technical issues. If anyone want to pick this topic up again, all you need to do is copy the code from said PR.

**Comment by KenavR** [comment]
If it is still available, I would take it.
