### ISSUE TITLE
Add favicon for each site

### ISSUE THREAD

**Issue by jgierer12** [webgems/webgems#164]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a neat idea I had to spice the site cards up a little: Add each site's favicon next to its title.

**Describe the solution you'd like**
This could be solved relative easily because Google has a favicon service. Just do an `<img src="https://www.google.com/s2/favicons?domain={url}" />`. Example:

```html
<img src="https://www.google.com/s2/favicons?domain=https://webgems.io" />
```

=> ![Webgems favicon](https://www.google.com/s2/favicons?domain=https://webgems.io/)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lostdesign** [comment]
Merged in #165
