### ISSUE TITLE
Add Codesignal.com to /general

### ISSUE THREAD

**Issue by jacobgasser** [webgems/webgems#200]
**Name**
CodeSignal.com

**Description**
(first of all sentences is spelled wrong in the issue template, "1-2 sentenses")
CodeSignal (formerly CodeFights) is an online programming tournament where you compete against real people in real time to try to finish the coding challenges first. You can play with random people, your friends, or they even have a single player arcade mode.

**URL**
https://codesignal.com

**Category**
tournament, peer-coding, any language

**Comment by lostdesign** [comment]
So, it costs $500/month per user to use it? Is that correct?

**Comment by ajs256** [comment]
I've opened a PR to add this resource, #234
