### ISSUE TITLE
Broken link CSS / 30 Seconds of CSS

### ISSUE THREAD

**Issue by ruffCode** [webgems/webgems#219]
**Describe the bug**
The link to this resource is outdated

Current link https://webgems.io/css?card=30secondsofcode should be updated to 
https://www.30secondsofcode.org/css/p/1

Thanks!

**Comment by lostdesign** [comment]
Thanks for submitting that bug. Are you looking into sending a PR or should I change it? @ruffCode

**Comment by lostdesign** [comment]
New link `https://www.30secondsofcode.org/css`

**Comment by ruffCode** [comment]
Just submitted the PR @lostdesign 

Thanks.
