### ISSUE TITLE
Missing WebAssembly Resources

### ISSUE THREAD

**Issue by 00ff0000red** [webgems/webgems#235]
Webgems has resources for multiple languages, yet lacks any mention of Wasm, although it might not be considered a "beginner" thing to learn about, but more of an advanced topic. Also, there might not be any generalized Wasm resources, as it's usually tied to the language that a program was written in, ex: Rust / C++.

Regardless, any resources might end up being helpful to somewhat experienced developers.

**Comment by lostdesign** [comment]
Totes fine with adding such section, if resources are either linked here or as PR.

**Comment by 00ff0000red** [comment]
I'm sorry, even I can't think of any non-language specific resources or tools, but maybe someone else would have some ideas?

**Comment by lostdesign** [comment]
I think it's ok to add WASM as a group and then have the languages mixed, its not like you jump into WASM before knowing any language ^^
