### ISSUE TITLE
Add some resources in category css, html, javascript, php, python.

### ISSUE THREAD

**Issue by programmerskp** [webgems/webgems#243]
I want to add some resources to the category:

- CSS
- HTML
- PHP
- JavaScript
- Python
#### CSS
https://www.w3schools.com/css/
#### HTML
https://www.w3schools.com/html/
#### PHP
https://www.w3schools.com/php/
#### JavaScript
https://www.w3schools.com/js/
#### Python
https://www.w3schools.com/python/

I think this could be helpful for the beginners to learn from these resources.

**Comment by OmarUsman** [comment]
W3 Schools is not a good source for info, Their info is usually outdated and there are many other sources which are more credible.

**Comment by lostdesign** [comment]
The point of webgems was to curate the best resources out there for people to have an easy start in web and find things they might not know yet. This is for beginners and intermediate people - therefore w3schools isn't a good match at all. The last time I've been going through w3schools, it had outdated things and overall is no really appealing. Thanks for the suggestion though anyways.

**Comment by programmerskp** [comment]
Thanks for replying.
