### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#46]
Add a quick search to be able to look for certain things.

**Comment by b3u** [comment]
I am interested in this, but i don't know vue.
Would this only search titles and tags?

**Comment by lostdesign** [comment]
@b3u thanks for your interest in this, you can more or less solve it by vanilla js. What you need to do is get the data from the `vuex` store/state and filter for the given keyword in the search. 

You can check this site: https://vuex.vuejs.org/guide/getters.html Vuex and the store are ready to be used, if you want i can guide/teach you on vue/vuex here. 

If you want, feel free to hop on our discord: https://devcord.com - you can catch me or others there to get some guideance if necessary. If not, you can always just ask here as well obviously.

**Comment by S3B4S** [comment]
Has been implemented
