### ISSUE TITLE
Some links

### ISSUE THREAD

**Issue by karl-police** [webgems/webgems#50]
I have some links that could be usefull for web related stuff or others:

https://codepen.io/carolineartz/full/ogVXZj

Color:
http://webcolourdata.com/
https://www.degraeve.com/ - has more tools
http://paletton.com/
https://color.adobe.com

Other:
https://www.mydevice.io/#compare-devices

http://shouldiprefix.com/
http://pleeease.io/play/

http://nicolasgallagher.com/micro-clearfix-hack/

https://hicksdesign.co.uk/boxmodel/

http://csszengarden.com/

**Comment by S3B4S** [comment]
Some have been added, thanks! @karl-police
