### ISSUE TITLE
Tag system

### ISSUE THREAD

**Issue by S3B4S** [webgems/webgems#52]
I can't live without a tag system on my bookmark manager. Often I'll search for the `#tag` instead of a title or category. This could be implemented alongside with #46. Thoughts?

**Comment by lostdesign** [comment]
Definitely! Maybe also related to #44. The data should be extended then the search should use these tags.

**Comment by S3B4S** [comment]
Ah yeah, I suggest having three fields; `price`, `author` (for credits) and `tags` for anything other than `price` and `author`.

**Comment by S3B4S** [comment]
I guess I could pick this up as the next "major" feature to add, a search bar that will initially search through titles and descriptions. Prepending a word with `#` will make it search through tags. 🤔

**Comment by S3B4S** [comment]
Wroking on this in #194

**Comment by S3B4S** [comment]
Has been implemented #194
