### ISSUE TITLE
Sorting of resources

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#70]
**Is your feature request related to a problem? Please describe.**
Currently people are adding the resources anywhere in the array which is not intended. No resource should be preferred over the other until the server with voting is implemented.

**Describe the solution you'd like**
Either on each load the resources are randomly sorted or by alphabet. Maybe for consistency it makes sense to sort them by alphabet but on the other hand when there is a search this might not be needed.

**Comment by karnthis** [comment]
I was thinking about this, and an alphabetical sort is pretty straight-forward. off the top of my head an addition something like this would probably do the trick:

```
computed: {
    category() {      
      return this.categories.find(category => category.title.toLowerCase() === this.categoryRouteTitle.toLowerCase())
    },
    orderedCategory() {
        return this.category().sort(this.compareTitles)
    }
  },
  methods: {
      compareTitles(x, y) {
        if (x.toLowerCase() >= y.toLowerCase()) {
            return 1
        } else {
            return -1
        }
      }
  }```

**Comment by S3B4S** [comment]
This has been implemented & merged. 😄
