### ISSUE TITLE
Tools was renamed to utility

### ISSUE THREAD

**Issue by lostdesign** [webgems/webgems#77]
Check #18, some commit has overwritten this change. Should be changed within the next commit.

**Comment by S3B4S** [comment]
That was done here https://github.com/webgems/webgems/pull/69/files#diff-e832e8f26403d95fac0ea1c59837588bR921. Before that the page was named `Utility` in the sidebar but the title of the page was `Tools`. So I copied over the title. But could easily be renamed to utility by just changing that title & slug.

**Comment by lostdesign** [comment]
fixed
